from train import Train

if __name__ == '__main__':

    path = "experiments"

    train = Train()

    experiments = [
        # NUS_WIDE 2100.10500
        {
            "dataset": "nus2100.10500",
            "loss": "loss_spring",
            "hash_size": 24,
            "margin": 0.5,
            "batch_size": 150,
            "total_epoch_count": 130,
            "number_of_epochs_per_decay": 100,
            "weight_decay_factor": 0.0002,
            "learning_rate": 0.07,
            "learning_rate_decay_factor": 2.0 / 3.0,
            "freeze": True,
        },
        {
            "dataset": "nus2100.10500",
            "loss": "loss_spring",
            "hash_size": 12,
            "margin": 0.5,
            "batch_size": 150,
            "total_epoch_count": 130,
            "number_of_epochs_per_decay": 100,
            "weight_decay_factor": 0.0002,
            "learning_rate": 0.07,
            "learning_rate_decay_factor": 2.0 / 3.0,
            "freeze": True,
        },
        {
            "dataset": "nus2100.10500",
            "loss": "loss_spring",
            "hash_size": 32,
            "margin": 0.5,
            "batch_size": 150,
            "total_epoch_count": 130,
            "number_of_epochs_per_decay": 100,
            "weight_decay_factor": 0.0002,
            "learning_rate": 0.07,
            "learning_rate_decay_factor": 2.0 / 3.0,
            "freeze": True,
        },
        {
            "dataset": "nus2100.10500",
            "loss": "loss_spring",
            "hash_size": 48,
            "margin": 0.5,
            "batch_size": 150,
            "total_epoch_count": 130,
            "number_of_epochs_per_decay": 100,
            "weight_decay_factor": 0.0002,
            "learning_rate": 0.07,
            "learning_rate_decay_factor": 2.0 / 3.0,
            "freeze": True,
        },
        {
            "dataset": "nus2100.10500",
            "loss": "loss_spring",
            "hash_size": 16,
            "margin": 0.5,
            "batch_size": 150,
            "total_epoch_count": 130,
            "number_of_epochs_per_decay": 100,
            "weight_decay_factor": 0.0002,
            "learning_rate": 0.07,
            "learning_rate_decay_factor": 2.0 / 3.0,
            "freeze": True,
        },
        {
            "dataset": "nus2100.10500",
            "loss": "loss_spring",
            "hash_size": 32,
            "margin": 0.5,
            "batch_size": 150,
            "total_epoch_count": 130,
            "number_of_epochs_per_decay": 100,
            "weight_decay_factor": 0.0002,
            "learning_rate": 0.07,
            "learning_rate_decay_factor": 2.0 / 3.0,
            "freeze": True,
        },
        {
            "dataset": "nus2100.10500",
            "loss": "loss_spring",
            "hash_size": 48,
            "margin": 0.5,
            "batch_size": 150,
            "total_epoch_count": 130,
            "number_of_epochs_per_decay": 100,
            "weight_decay_factor": 0.0002,
            "learning_rate": 0.07,
            "learning_rate_decay_factor": 2.0 / 3.0,
            "freeze": True,
        },
        
        
        # NUS_WIDE 5000.10000
        {
            "dataset": "nus5000.10000",
            "loss": "loss_spring",
            "hash_size": 24,
            "margin": 0.5,
            "batch_size": 150,
            "total_epoch_count": 130,
            "number_of_epochs_per_decay": 100,
            "weight_decay_factor": 0.0002,
            "learning_rate": 0.07,
            "learning_rate_decay_factor": 2.0 / 3.0,
            "freeze": True,
        },
        {
            "dataset": "nus5000.10000",
            "loss": "loss_spring",
            "hash_size": 16,
            "margin": 0.5,
            "batch_size": 150,
            "total_epoch_count": 130,
            "number_of_epochs_per_decay": 100,
            "weight_decay_factor": 0.0002,
            "learning_rate": 0.07,
            "learning_rate_decay_factor": 2.0 / 3.0,
            "freeze": True,
        },
        {
            "dataset": "nus5000.10000",
            "loss": "loss_spring",
            "hash_size": 32,
            "margin": 0.5,
            "batch_size": 150,
            "total_epoch_count": 130,
            "number_of_epochs_per_decay": 100,
            "weight_decay_factor": 0.0002,
            "learning_rate": 0.07,
            "learning_rate_decay_factor": 2.0 / 3.0,
            "freeze": True,
        },
        {
            "dataset": "nus5000.10000",
            "loss": "loss_spring",
            "hash_size": 8,
            "margin": 0.5,
            "batch_size": 150,
            "total_epoch_count": 130,
            "number_of_epochs_per_decay": 100,
            "weight_decay_factor": 0.0002,
            "learning_rate": 0.07,
            "learning_rate_decay_factor": 2.0 / 3.0,
            "freeze": True,
        },

        # NUS_WIDE 2100._
        {
            "dataset": "nus2100._",
            "loss": "loss_spring",
            "hash_size": 24,
            "margin": 2.0,
            "batch_size": 150,
            "total_epoch_count": 35,
            "number_of_epochs_per_decay": 30,
            "weight_decay_factor": 5e-05,
            "learning_rate": 0.05,
            "learning_rate_decay_factor": 2.0 / 3.0
        },
        {
            "dataset": "nus2100._",
            "loss": "loss_spring",
            "hash_size": 16,
            "margin": 2.0,
            "batch_size": 150,
            "total_epoch_count": 35,
            "number_of_epochs_per_decay": 30,
            "weight_decay_factor": 5e-05,
            "learning_rate": 0.05,
            "learning_rate_decay_factor": 2.0 / 3.0
        },
        {
            "dataset": "nus2100._",
            "loss": "loss_spring",
            "hash_size": 32,
            "margin": 2.0,
            "batch_size": 150,
            "total_epoch_count": 35,
            "number_of_epochs_per_decay": 30,
            "weight_decay_factor": 5e-05,
            "learning_rate": 0.05,
            "learning_rate_decay_factor": 2.0 / 3.0
        },
        {
            "dataset": "nus2100._",
            "loss": "loss_spring",
            "hash_size": 48,
            "margin": 2.0,
            "batch_size": 150,
            "total_epoch_count": 35,
            "number_of_epochs_per_decay": 30,
            "weight_decay_factor": 5e-05,
            "learning_rate": 0.05,
            "learning_rate_decay_factor": 2.0 / 3.0
        },

        ###########################################################
        {
            "dataset": "nus2100.10500",
            "loss": "loss_spring",
            "hash_size": 8,
            "margin": 2.0,
            "batch_size": 150,
            "total_epoch_count": 200,
            "number_of_epochs_per_decay": 100,
            "weight_decay_factor": 5e-05,
            "learning_rate": 0.05,
            "learning_rate_decay_factor": 2.0 / 3.0
        },
        {
            "dataset": "nus2100.10500",
            "loss": "loss_spring",
            "hash_size": 4,
            "margin": 2.0,
            "batch_size": 150,
            "total_epoch_count": 200,
            "number_of_epochs_per_decay": 100,
            "weight_decay_factor": 5e-05,
            "learning_rate": 0.05,
            "learning_rate_decay_factor": 2.0 / 3.0
        },
        {
            "dataset": "nus2100._",
            "loss": "loss_spring",
            "hash_size": 8,
            "margin": 2.0,
            "batch_size": 150,
            "total_epoch_count": 35,
            "number_of_epochs_per_decay": 30,
            "weight_decay_factor": 5e-05,
            "learning_rate": 0.05,
            "learning_rate_decay_factor": 2.0 / 3.0
        },
        {
            "dataset": "nus2100._",
            "loss": "loss_spring",
            "hash_size": 4,
            "margin": 2.0,
            "batch_size": 150,
            "total_epoch_count": 35,
            "number_of_epochs_per_decay": 30,
            "weight_decay_factor": 5e-05,
            "learning_rate": 0.05,
            "learning_rate_decay_factor": 2.0 / 3.0
        },
        {
            "dataset": "nus5000.10000",
            "loss": "loss_spring",
            "hash_size": 4,
            "margin": 2.0,
            "batch_size": 150,
            "total_epoch_count": 200,
            "number_of_epochs_per_decay": 100,
            "weight_decay_factor": 5e-05,
            "learning_rate": 0.05,
            "learning_rate_decay_factor": 2.0 / 3.0
        },
        {
            "dataset": "nus5000.10000",
            "loss": "loss_spring",
            "hash_size": 48,
            "margin": 2.0,
            "batch_size": 150,
            "total_epoch_count": 200,
            "number_of_epochs_per_decay": 100,
            "weight_decay_factor": 5e-05,
            "learning_rate": 0.05,
            "learning_rate_decay_factor": 2.0 / 3.0
        },
        ###########################################################
        {
            "dataset": "nus2100.10500",
            "loss": "loss_accv_mod",
            "hash_size": 24,
            "margin": 0.5,
            "batch_size": 150,
            "total_epoch_count": 200,
            "number_of_epochs_per_decay": 100,
            "weight_decay_factor": 5e-05,
            "learning_rate": 0.05,
            "learning_rate_decay_factor": 2.0 / 3.0
        },
        {
            "dataset": "nus2100.10500",
            "loss": "loss_accv_mod",
            "hash_size": 16,
            "margin": 0.5,
            "batch_size": 150,
            "total_epoch_count": 200,
            "number_of_epochs_per_decay": 100,
            "weight_decay_factor": 5e-05,
            "learning_rate": 0.05,
            "learning_rate_decay_factor": 2.0 / 3.0
        },
        {
            "dataset": "nus2100.10500",
            "loss": "loss_accv_mod",
            "hash_size": 8,
            "margin": 0.5,
            "batch_size": 150,
            "total_epoch_count": 200,
            "number_of_epochs_per_decay": 100,
            "weight_decay_factor": 5e-05,
            "learning_rate": 0.05,
            "learning_rate_decay_factor": 2.0 / 3.0
        },
        {
            "dataset": "nus2100.10500",
            "loss": "loss_accv_mod",
            "hash_size": 4,
            "margin": 0.5,
            "batch_size": 150,
            "total_epoch_count": 200,
            "number_of_epochs_per_decay": 100,
            "weight_decay_factor": 5e-05,
            "learning_rate": 0.05,
            "learning_rate_decay_factor": 2.0 / 3.0
        },
        {
            "dataset": "nus2100.10500",
            "loss": "loss_accv_mod",
            "hash_size": 32,
            "margin": 0.5,
            "batch_size": 150,
            "total_epoch_count": 200,
            "number_of_epochs_per_decay": 100,
            "weight_decay_factor": 5e-05,
            "learning_rate": 0.05,
            "learning_rate_decay_factor": 2.0 / 3.0
        },
        {
            "dataset": "nus2100.10500",
            "loss": "loss_accv_mod",
            "hash_size": 48,
            "margin": 0.5,
            "batch_size": 150,
            "total_epoch_count": 200,
            "number_of_epochs_per_decay": 100,
            "weight_decay_factor": 5e-05,
            "learning_rate": 0.05,
            "learning_rate_decay_factor": 2.0 / 3.0
        },

        {
            "dataset": "nus2100._",
            "loss": "loss_accv_mod",
            "hash_size": 24,
            "margin": 0.5,
            "batch_size": 150,
            "total_epoch_count": 35,
            "number_of_epochs_per_decay": 30,
            "weight_decay_factor": 5e-05,
            "learning_rate": 0.05,
            "learning_rate_decay_factor": 2.0 / 3.0
        },
        {
            "dataset": "nus2100._",
            "loss": "loss_accv_mod",
            "hash_size": 16,
            "margin": 0.5,
            "batch_size": 150,
            "total_epoch_count": 35,
            "number_of_epochs_per_decay": 30,
            "weight_decay_factor": 5e-05,
            "learning_rate": 0.05,
            "learning_rate_decay_factor": 2.0 / 3.0
        },
        {
            "dataset": "nus2100._",
            "loss": "loss_accv_mod",
            "hash_size": 8,
            "margin": 0.5,
            "batch_size": 150,
            "total_epoch_count": 35,
            "number_of_epochs_per_decay": 30,
            "weight_decay_factor": 5e-05,
            "learning_rate": 0.05,
            "learning_rate_decay_factor": 2.0 / 3.0
        },
        {
            "dataset": "nus2100._",
            "loss": "loss_accv_mod",
            "hash_size": 4,
            "margin": 0.5,
            "batch_size": 150,
            "total_epoch_count": 35,
            "number_of_epochs_per_decay": 30,
            "weight_decay_factor": 5e-05,
            "learning_rate": 0.05,
            "learning_rate_decay_factor": 2.0 / 3.0
        },
        {
            "dataset": "nus2100._",
            "loss": "loss_accv_mod",
            "hash_size": 32,
            "margin": 0.5,
            "batch_size": 150,
            "total_epoch_count": 35,
            "number_of_epochs_per_decay": 30,
            "weight_decay_factor": 5e-05,
            "learning_rate": 0.05,
            "learning_rate_decay_factor": 2.0 / 3.0
        },
        {
            "dataset": "nus2100._",
            "loss": "loss_accv_mod",
            "hash_size": 48,
            "margin": 0.5,
            "batch_size": 150,
            "total_epoch_count": 35,
            "number_of_epochs_per_decay": 30,
            "weight_decay_factor": 5e-05,
            "learning_rate": 0.05,
            "learning_rate_decay_factor": 2.0 / 3.0
        },

        {
            "dataset": "nus5000.10000",
            "loss": "loss_accv_mod",
            "hash_size": 24,
            "margin": 0.5,
            "batch_size": 150,
            "total_epoch_count": 150,
            "number_of_epochs_per_decay": 10.0,
            "weight_decay_factor": 0.0005,
            "learning_rate": 0.1,
            "learning_rate_decay_factor": 2.0 / 3.0
        },
        {
            "dataset": "nus5000.10000",
            "loss": "loss_accv_mod",
            "hash_size": 16,
            "margin": 0.5,
            "batch_size": 150,
            "total_epoch_count": 150,
            "number_of_epochs_per_decay": 10.0,
            "weight_decay_factor": 0.0005,
            "learning_rate": 0.1,
            "learning_rate_decay_factor": 2.0 / 3.0
        },
        {
            "dataset": "nus5000.10000",
            "loss": "loss_accv_mod",
            "hash_size": 8,
            "margin": 0.5,
            "batch_size": 150,
            "total_epoch_count": 150,
            "number_of_epochs_per_decay": 10.0,
            "weight_decay_factor": 0.0005,
            "learning_rate": 0.1,
            "learning_rate_decay_factor": 2.0 / 3.0
        },
        {
            "dataset": "nus5000.10000",
            "loss": "loss_accv_mod",
            "hash_size": 4,
            "margin": 0.5,
            "batch_size": 150,
            "total_epoch_count": 150,
            "number_of_epochs_per_decay": 10.0,
            "weight_decay_factor": 0.0005,
            "learning_rate": 0.1,
            "learning_rate_decay_factor": 2.0 / 3.0
        },
        {
            "dataset": "nus5000.10000",
            "loss": "loss_accv_mod",
            "hash_size": 32,
            "margin": 0.5,
            "batch_size": 150,
            "total_epoch_count": 150,
            "number_of_epochs_per_decay": 10.0,
            "weight_decay_factor": 0.0005,
            "learning_rate": 0.1,
            "learning_rate_decay_factor": 2.0 / 3.0
        },
        {
            "dataset": "nus5000.10000",
            "loss": "loss_accv_mod",
            "hash_size": 48,
            "margin": 0.5,
            "batch_size": 150,
            "total_epoch_count": 150,
            "number_of_epochs_per_decay": 10.0,
            "weight_decay_factor": 0.0005,
            "learning_rate": 0.1,
            "learning_rate_decay_factor": 2.0 / 3.0
        },

        
        # {
        #     "loss": "loss_accv",
        #     "hash_size": 24,
        #     "margin": 12,
        #     "batch_size": 150,
        #     "total_epoch_count": 100,
        #     "number_of_epochs_per_decay": 20.0,
        #     "weight_decay_factor": 0.0011,
        #     "learning_rate": 0.000225,
        #     "learning_rate_decay_factor": 2.0 / 3.0
        # },
        # {
        #     "loss": "loss_accv",
        #     "hash_size": 24,
        #     "margin": 12,
        #     "batch_size": 150,
        #     "total_epoch_count": 100,
        #     "number_of_epochs_per_decay": 20.0,
        #     "weight_decay_factor": 0.0012,
        #     "learning_rate": 0.001,
        #     "learning_rate_decay_factor": 2.0 / 3.0
        # },
        # {
        #     "loss": "loss_accv_mod",
        #     "hash_size": 24,
        #     "margin": 0.5,
        #     "batch_size": 150,
        #     "total_epoch_count": 70,
        #     "number_of_epochs_per_decay": 20.0,
        #     "weight_decay_factor": 0.00005,
        #     "learning_rate": 0.03,
        #     "learning_rate_decay_factor": 2.0 / 3.0
        # },
        # {
        #     "loss": "loss_accv_mod",
        #     "hash_size": 24,
        #     "margin": 0.5,
        #     "batch_size": 150,
        #     "total_epoch_count": 70,
        #     "number_of_epochs_per_decay": 20.0,
        #     "weight_decay_factor": 0.00005,
        #     "learning_rate": 0.05,
        #     "learning_rate_decay_factor": 2.0 / 3.0
        # },
        # {
        #     "loss": "loss_accv_mod",
        #     "hash_size": 24,
        #     "margin": 0.5,
        #     "batch_size": 150,
        #     "total_epoch_count": 70,
        #     "number_of_epochs_per_decay": 20.0,
        #     "weight_decay_factor": 0.00005,
        #     "learning_rate": 0.05,
        #     "learning_rate_decay_factor": 2.0 / 3.0
        # },
        # {
        #     "loss": "loss_accv_mod",
        #     "hash_size": 24,
        #     "margin": 0.5,
        #     "batch_size": 150,
        #     "total_epoch_count": 100,
        #     "number_of_epochs_per_decay": 20.0,
        #     "weight_decay_factor": 0.00005,
        #     "learning_rate": 0.06,
        #     "learning_rate_decay_factor": 2.0 / 3.0
        # },
        # {
        #     "loss": "loss_accv_mod",
        #     "hash_size": 24,
        #     "margin": 0.5,
        #     "batch_size": 150,
        #     "total_epoch_count": 70,
        #     "number_of_epochs_per_decay": 20.0,
        #     "weight_decay_factor": 0.00005,
        #     "learning_rate": 0.07,
        #     "learning_rate_decay_factor": 2.0 / 3.0
        # },
        # {
        #     "loss": "loss_accv_mod",
        #     "hash_size": 24,
        #     "margin": 0.5,
        #     "batch_size": 150,
        #     "total_epoch_count": 70,
        #     "number_of_epochs_per_decay": 20.0,
        #     "weight_decay_factor": 0.00005,
        #     "learning_rate": 0.08,
        #     "learning_rate_decay_factor": 2.0 / 3.0
        # },
        # {
        #     "loss": "loss_accv_mod",
        #     "hash_size": 24,
        #     "margin": 0.5,
        #     "batch_size": 150,
        #     "total_epoch_count": 70,
        #     "number_of_epochs_per_decay": 20.0,
        #     "weight_decay_factor": 0.00005,
        #     "learning_rate": 0.09,
        #     "learning_rate_decay_factor": 2.0 / 3.0
        # },
        # {
        #     "loss": "loss_accv_mod",
        #     "hash_size": 24,
        #     "margin": 0.5,
        #     "batch_size": 150,
        #     "total_epoch_count": 100,
        #     "number_of_epochs_per_decay": 20.0,
        #     "weight_decay_factor": 0.00005,
        #     "learning_rate": 0.024,
        #     "learning_rate_decay_factor": 2.0 / 3.0
        # },
        # {
        #     "loss": "loss_triplet",
        #     "hash_size": 24,
        #     "margin": 2.0,
        #     "batch_size": 150,
        #     "total_epoch_count": 200,
        #     "number_of_epochs_per_decay": 67.0,
        #     "weight_decay_factor": 5.0e-5,
        #     "learning_rate": 0.025,
        #     "learning_rate_decay_factor": 2.0 / 3.0
        # },
        # {
        #     "loss": "loss_spring",
        #     "hash_size": 24,
        #     "margin": 2.0,
        #     "batch_size": 150,
        #     "total_epoch_count": 150,
        #     "number_of_epochs_per_decay": 150.0,
        #     "weight_decay_factor": 5.0e-5,
        #     "learning_rate": 0.020,
        #     "learning_rate_decay_factor": 2.0 / 3.0
        # },
        # {
        #     "loss": "loss_spring",
        #     "hash_size": 24,
        #     "margin": 2.0,
        #     "batch_size": 150,
        #     "total_epoch_count": 150,
        #     "number_of_epochs_per_decay": 150.0,
        #     "weight_decay_factor": 5.0e-5,
        #     "learning_rate": 0.030,
        #     "learning_rate_decay_factor": 2.0 / 3.0
        # },
        # {
        #     "loss": "loss_accv",
        #     "hash_size": 12,
        #     "margin": 6,
        #     "batch_size": 150,
        #     "total_epoch_count": 100,
        #     "number_of_epochs_per_decay": 20.0,
        #     "weight_decay_factor": 0.0012,
        #     "learning_rate": 0.001,
        #     "learning_rate_decay_factor": 2.0 / 3.0
        # },
        # {
        #     "loss": "loss_accv_mod",
        #     "hash_size": 12,
        #     "margin": 0.5,
        #     "batch_size": 150,
        #     "total_epoch_count": 200,
        #     "number_of_epochs_per_decay": 67.0,
        #     "weight_decay_factor": 5.0e-5,
        #     "learning_rate": 0.02,
        #     "learning_rate_decay_factor": 2.0 / 3.0
        # },
        # {
        #     "loss": "loss_triplet",
        #     "hash_size": 12,
        #     "margin": 2.0,
        #     "batch_size": 150,
        #     "total_epoch_count": 200,
        #     "number_of_epochs_per_decay": 67.0,
        #     "weight_decay_factor": 5.0e-5,
        #     "learning_rate": 0.025,
        #     "learning_rate_decay_factor": 2.0 / 3.0
        # },
        # {
        #     "loss": "loss_spring",
        #     "hash_size": 12,
        #     "margin": 2.0,
        #     "batch_size": 150,
        #     "total_epoch_count": 100,
        #     "number_of_epochs_per_decay": 67.0,
        #     "weight_decay_factor": 5.0e-5,
        #     "learning_rate": 0.020,
        #     "learning_rate_decay_factor": 2.0 / 3.0
        # },
        # {
        #     "loss": "loss_accv",
        #     "hash_size": 32,
        #     "margin": 16,
        #     "batch_size": 150,
        #     "total_epoch_count": 100,
        #     "number_of_epochs_per_decay": 20.0,
        #     "weight_decay_factor": 0.0012,
        #     "learning_rate": 0.001,
        #     "learning_rate_decay_factor": 2.0 / 3.0
        # },
        # {
        #     "loss": "loss_accv_mod",
        #     "hash_size": 32,
        #     "margin": 0.5,
        #     "batch_size": 150,
        #     "total_epoch_count": 200,
        #     "number_of_epochs_per_decay": 67.0,
        #     "weight_decay_factor": 5.0e-5,
        #     "learning_rate": 0.02,
        #     "learning_rate_decay_factor": 2.0 / 3.0
        # },
        # {
        #     "loss": "loss_triplet",
        #     "hash_size": 32,
        #     "margin": 2.0,
        #     "batch_size": 150,
        #     "total_epoch_count": 200,
        #     "number_of_epochs_per_decay": 67.0,
        #     "weight_decay_factor": 5.0e-5,
        #     "learning_rate": 0.025,
        #     "learning_rate_decay_factor": 2.0 / 3.0
        # },
        # {
        #     "loss": "loss_spring",
        #     "hash_size": 32,
        #     "margin": 2.0,
        #     "batch_size": 150,
        #     "total_epoch_count": 100,
        #     "number_of_epochs_per_decay": 67.0,
        #     "weight_decay_factor": 5.0e-5,
        #     "learning_rate": 0.020,
        #     "learning_rate_decay_factor": 2.0 / 3.0
        # }
    ]

    for e in experiments:
        train.run(path, e)
